### ISSUE TITLE
Hashtags are messed up

### ISSUE THREAD

**Issue by MalcolmK** [Swatto/td#13]
Hey @Swatto,

After I restarted my Macbook Air, the todos are messed up. I have added a screenshot below, what can I do to fix this? It is repeating the first hashtag at the places of the other hashtags.

![image](https://cloud.githubusercontent.com/assets/2427717/6203455/cc8adfaa-b523-11e4-9dfc-257cdb3f29ef.png)

Malcolm

**Comment by MalcolmK** [comment]
How can I get the latest version of this todo on my mac?

**Comment by Swatto** [comment]
If you have go installed and working on your machine, you could build it from source. If you don't have, I'm waiting a PR for windows support so you will need to wait until that (I will release an other version at that point)

**Comment by Swatto** [comment]
@MalcolmK the issue is fixed and the last release is published.

**Comment by MalcolmK** [comment]
This is the first time I'm using a go plugin, so I'm kinda noob. Will my local version automatically be updated? Do I have to take ANY kind of actions?

**Comment by Swatto** [comment]
Just replace the `td` executable file with the downloaded one.
