### ISSUE TITLE
It is better to use gofmt.

### ISSUE THREAD

**Issue by suzukaze** [Swatto/td#14]
td is a nice command line tool.

Generally Go format is hard tab format.

As we use gofmt, it is easy for contributor to send a pull request. Example I set hard tab format in vim for go.( set soft tab in vim for ruby)

gofmt:
```
$ gofmt -w cli.go
$ gofmt -w collection.go
$ gofmt -w todo.go
```

**Comment by Swatto** [comment]
Thanks for the tip, I will look for sure at _gofmt_. But since the project is now using tabs instead of spaces so we won't have that issue again.
