### ISSUE TITLE
Unstable spaces added to output

### ISSUE THREAD

**Issue by Swatto** [Swatto/td#16]
In the last release, I made the switch to `daviddengcn/go-colortext` to support windows using the code of @mattn. But it looks unstable now.

![screenshot](https://cloud.githubusercontent.com/assets/892951/6226478/da44ed02-b695-11e4-875b-21835954b806.png)

This screenshot is without any change in the collection or in the code.

**Comment by mattn** [comment]
I can't reproduce it.

http://go-gyazo.appspot.com/2cd38731576e47f8.png

**Comment by Swatto** [comment]
Ok, it was my tmux configuration.
