### ISSUE TITLE
Give more help on invocation error

### ISSUE THREAD

**Issue by nicolaiskogheim** [Swatto/td#24]
> td will look at a .todos files to store your todos (like Git does: it will try recursively in each parent folder). This permit to have different list of todos per folder.

This is a great feature that I didn't know about until a friend just pointed it out to me.
I was looking for a simple todo-manager the other day, installed this, and ran it straight away.
The error message suggests to add a todo.json and set an environment variable, which is an okey solution if that's what you're after. I was not, and almost wrote a script to fit my needs.

My point and suggestion to you: include the text I referenced in the error message that `td` produces when there is no todo-file. Don't let the laziness of some users deprive them of one of this utility's greatest features :)

**Comment by Swatto** [comment]
Hi !
Sorry but I don't catch your issue or your proposition in that particular case.

**Comment by nicolaiskogheim** [comment]
This is the error message when `td` doesn't understand what to do:
```sh
 $ td

Error
The environment variable "TODO_DB_PATH" must be set.
Example: "export TODO_DB_PATH=$HOME/Dropbox/todo.json" in your .bash_profile

open : no such file or directory
```

I only suggest that this error message should inform about the alternative, which is to add a `.todos`-file.
And besides, the error message as it stands now, is wrong. "The environment variable TODO_DB_PATH MUST be set" is not true, as you can have a `.todos`-file and not set the env variable.

**Comment by Swatto** [comment]
You're right ! This message is not true anymore. I'm gonna change this in two weeks when I'll be back. Thanks for the highlight.

**Comment by nicolaiskogheim** [comment]
Sweet :) Keep up the good work!

**Comment by Swatto** [comment]
It's done: it will be shipped in the next release. Thanks for your feedback !
