### ISSUE TITLE
Commands aren't escaped

### ISSUE THREAD

**Issue by aratno** [Swatto/td#26]
If I enter `td a ls`, I get a new bullet with the contents of the current folder (piped from the `ls` command) in the list. This breaks rendering if `clear` is part of a command, and certainly could lead to some significantly more serious behaviors.

**Comment by Swatto** [comment]
This is a real issue. I will take a look at this soon. Thanks for the reporting.

**Comment by aratno** [comment]
<img width="618" alt="screenshot 2015-10-28 20 31 08" src="https://cloud.githubusercontent.com/assets/8835036/10807148/df6729d2-7db2-11e5-96c6-e9170bca8e0a.png">

In trying to replicate the behavior I found a whole new issue. What could this be?

**Comment by Swatto** [comment]
I really don't know since I never saw this. Could you give me details about your system?

**Comment by aratno** [comment]
I'm on OSX 10.11 with zsh 5.0.8 (x86_64-apple-darwin15.0)

**Comment by aratno** [comment]
<img width="600" alt="screenshot 2015-10-29 11 05 01" src="https://cloud.githubusercontent.com/assets/8835036/10822301/eed0794e-7e2c-11e5-9c1e-c287bbe7ab30.png">

**Comment by Swatto** [comment]
Well since you run a shell sub-command, I can't escape it.
I have the same result with a simple _echo_ command: `echo "`ls`"`.

**Comment by aratno** [comment]
Got it. I was having very weird behaviors when writing an item that included `clear`, but I suppose there's no way around that.

**Comment by Swatto** [comment]
You would have the same issue if you run this (it's also a sub-command):
```bash
td a $(ls)
```
