### ISSUE TITLE
Usage of `reorder` very unclear

### ISSUE THREAD

**Issue by aratno** [Swatto/td#27]
Documentation/purpose of reorder is very unclear. I can't even figure out how to make it do anything.

Am I able to swap elements? If I remove the first element of my list and clean, I still have a list starting with the second element. If I want to swap two elements, I would assume `td r 3 2` would swap the second and third elements. If I want my list to be reordered, I would assume `td r` would do this, but neither intuitive command does anything.

If you explain these, I'd be glad to fix the documentation.

**Comment by Swatto** [comment]
The behavior of the *reorder* is to to reset `id` of todos. As an example, if you have two todos with id `3` and `10`, both will receive new `id` (as low as possible) like `1` and `2` if they are available.

**Comment by aratno** [comment]
Is there any way to swap items then? Sometimes it's nice to keep an item near the top of a list, even if you don't remember to add it until later.

I think the reorder behavior you mentioned could be called with `td r` and the swap could be called with `td r 3 2`, like I mentioned. What do you think?

**Comment by Swatto** [comment]
I like the idea to swap with the reorder: I will do this in few days.

**Comment by Swatto** [comment]
I know I'm more than late but I found the time to do it. If you are still interested, could you have a look on the pre-release with the swap?
