### ISSUE TITLE
Improve line breaks

### ISSUE THREAD

**Issue by aratno** [Swatto/td#29]
It would be absolutely beautiful if the lines broke at the nearest space (or hyphenated, whatever works best), such that instead of this:

```
1 | ✕ Curabitur magna leo, condimentum quis eleif
end et
2 | ✕ Donec aliquam tellus vitae leo eleifend, et vestibulum
3 | ✕ In quis interdum nisl
```

It looks like this:

```
1 | ✕ Curabitur magna leo, condimentum quis
      eleifend et
2 | ✕ Donec aliquam tellus vitae leo eleifend, et vestibulum
3 | ✕ In quis interdum nisl
```

**Comment by Swatto** [comment]
I definitely agree with this. I will do it.

**Comment by aratno** [comment]
I'm not sure what you mean.
The line break is not part of the list item. It simply comes up when rendering the items. Although I don't know Go, I assume you would have to get the width of the terminal window, then the length of the item string, and add a line break and space offset if the length of the item exceeds the width of the window. 

Does this help clarify?
If the item string is `This is an item I want to remember`, and there are only enough spaces to display until the second `m` of `remember`, then render the string with a newline instead of a space (before `remember`) and add spaces so the first character in the second line is aligned with the first character of the first line, like this:
<pre>
<code>
1 | ✕ This is an item I want to
      remember
</code>
</pre>

**Comment by Swatto** [comment]
It's clear.
After some search, this will require a project like a termbox implementation which cause weight and instability to support terminal on every platform.

I would like your opinion @txgruppi between the cost (stability and weight) and the feature. I really want stability on every platform for this project.

**Comment by txgruppi** [comment]
It is possible to use `stty size` on Linux and OSX to find out how many lines and columns the current terminal have. I'm not sure about how it would work on Windows.

I don't think it is complicated and until we find out how to make it work on Windows we can just print the *pretty* line breaks on system wich have `stty`.

We have to keep in mind that this **will not** react to window resize. After the text is printed it is the terminal's responsability to make it fit if the window size is reduced.

To make it react to the window resize we would have to make 'td' become something like `vim`, a process that *get* the screen and stays there listening to events.

Any other idea is welcome.

Cheers.

**Comment by Swatto** [comment]
I'm ok with the idea of `stty` but not with the proposition to get the screen (it's way to much for a simple CLI). I'm gonna work on this in a few days because I'm very busy for the moment for my day job.

**Comment by txgruppi** [comment]
I was looking for another solutions for windows and I saw that `github.com/nsf/termbox-go` is a pure go library with Windows support for features.

We could use this library to get the information or we could just *copy* the code responsible for making it work.

I believe if there is no performance problems we can use the library, I will try to get a Windows VM working later today to check it. Another advantage is that it is crossplatform, so it would also work for Linux and OSX.

The code with the library would be

```go
package main

import (
    "fmt"

    "github.com/nsf/termbox-go"
)

func main() {
    if err := termbox.Init(); err != nil {
        panic(err)
    }
    w, h := termbox.Size()
    termbox.Close()
    fmt.Println(w, h)
}
```

To *copy* the code check the links:

https://github.com/nsf/termbox-go/blob/master/api_windows.go#L30
https://github.com/nsf/termbox-go/blob/master/termbox_windows.go#L392
https://github.com/nsf/termbox-go/blob/master/api_windows.go#L176
https://github.com/nsf/termbox-go/blob/master/api_windows.go#L90

PS: By reading termbox's code I believe that `csbi.srWindow.Right - csbi.srWindow.Left + 1` returns the window size but not the number of columns, which can be influenced by font configuration. Check the second link from the list above to see termbox's solution.
