### ISSUE TITLE
Reordering by specifying a list

### ISSUE THREAD

**Issue by yageek** [Swatto/td#32]
It would be nice to be able to reorder the list by specifying a list of ID.

Let's have this list: 
1. A
2. B
3. C
4. D

I would like to reorder some part of it by writing `td reorder 4 3`. So the list will become:
1. D
2. C
3. A
2. B

**Comment by Swatto** [comment]
The usage of `reorder` with two arguments is to swap their positions and not making the assumption that you want them to be at the top of the list.
You can use this behavior to achieve exactly what you ask for:

1. `td reorder 1 4`
2. `td reorder 2 3`
3. `td reorder 3 4`
