### ISSUE TITLE
Release sha changed

### ISSUE THREAD

**Issue by andig** [Swatto/td#38]
Noticed during Homebrew/homebrew-core#78666 that the release sha has changed.

```
❯ brew install --build-from-source td
==> Downloading https://github.com/Swatto/td/archive/1.4.1.tar.gz
==> Downloading from https://codeload.github.com/Swatto/td/tar.gz/1.4.1
#=#=#
Error: SHA256 mismatch
Expected: fe81605196e9c1f9c5f930adf5067d0c0cb90e9c83c6a2d846e12dc0a18dd7e3
  Actual: 1fc8dcc1ad318be1a9f047fe617e8d93f33dcc6b09dde3accaa30417ff007bb5
    File: /Users/andig/Library/Caches/Homebrew/downloads/8d84a8ee4a82715a0e71413bfb37aa1f8dda5b3ed182db5b1c8c72512cad6491--td-1.4.1.tar.gz
```

Has this been re-released?

**Comment by Swatto** [comment]
Not that I remember but maybe. I'm pretty behind in terms of golang version anyway.
If that help, I could bump some version number to create a new release.

**Comment by andig** [comment]
It would be sufficient to confirm that it actually has been updated. If you want to do a new point release anyway, we could also use that of course.

**Comment by Swatto** [comment]
I've done a new release (1.4.2) in case you want to take action on it already

**Comment by andig** [comment]
Great, thank you!
